### PR TITLE
chore: Updated `http` to 1.1.0

### PR DESCRIPTION
**Pull request by DCampagnola**
## About the changes
Updated `http` dependency to `1.1.0` to support Dart 3.0.
Updated also Dart dependency to 3.0 or later.

### Important files
pubspec.yaml

## Discussion points

Are there any issues with this dependency update?

### CODE REVIEW

**Comment by kwasniew** [comment]
Hi @DCampagnola Thanks for the PR. Do you know any stats about the usage rate of Dart SDK 2 vs SDK 3? Since this PR would drop the support for the older version I'd like to better understand the impact on Flutter devs using older versions.

**Comment by DCampagnola** [comment]
Great question!
I have found that a lot of packages are starting to support `3.X.X` and pub.dev is reporting the compatibility with Dart 3.
The reason I dropped support of Dart 2.x is that `http` package dropped the support with the version `1.0`. 
Another way to support both versions without dropping support would be setting the dependency of http to 
`>=0.13.6 <2.0.0` and Dart to `>=2.18.6 <4.0.0`. I’ve seen this in other packages that depend on http.

**Comment by kwasniew** [comment]
@DCampagnola it sounds good. Can you update the deps to be as inclusive as possible and we'll merge it soon. Also, can you link me to a popular project that already adopted this convention?

**Review by DCampagnola — COMMENTED** [review]
I updated the pubspec file to include the previous versions.
[Here](https://pub.dev/packages?q=dependency%3Ahttp&sort=popularity) are the most popular packages that have http as dependency. They are all starting to support Dart 3.0 and the most used approach is the one proposed with this commit. An example is the [pubspec file](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/package_info_plus/package_info_plus/pubspec.yaml) of the popular package_info_plus package.

**Comment by kwasniew** [comment]
@DCampagnola Thanks for updating the deps and providing more background. Let's merge it.

**Review by kwasniew — APPROVED** [review]

**Pull request merged**
