### PR TITLE
feat: added variant payload support

### LINKED ISSUE #11: Access Payload data of Variants
### Describe the feature request

Variants can include payload. It would be nice to get access to that data. In other Unleash SDKs variants contains a ```payload``` field

### Background

One usage I currently need is to initialise a field with a threshold value based on a variant.
I could use the name but the payload part of a Variant is exactly what I need to use. 

### Solution suggestions

Add the Payload objet to the Variant one like in other official SDKs.

### PR DESCRIPTION
**Pull request by mikklfr**
## About the changes

This PR adds support of Payload object inside Variants one. Approach is similar to the Android SDK:
https://github.com/Unleash/unleash-android-proxy-sdk/blob/main/src/main/kotlin/io/getunleash/data/Variant.kt
https://github.com/Unleash/unleash-android-proxy-sdk/blob/main/src/main/kotlin/io/getunleash/data/Payload.kt

Closes #11

### Important files

- payload.dart
- toggle_config_test.dart
- unleash_proxy_client_flutter_test.dart
- variant.dart
- README.md

## Discussion points

This is my first PR to your repository, I updated the mapping, tests and a bit of documentation, feel free to add requirements

### CODE REVIEW

**Comment by pransh15** [comment]
Hey @mikklfr 👋
Someone from the team to review soon. Thank you so much for the PR!

**Comment by mikklfr** [comment]
I fixed the formatting issue in the test file (missing new line), if you can relaunch a workflow 🙏

**Comment by kwasniew** [comment]
@mikklfr I went through your changes and it looks awesome.

**Review by kwasniew — APPROVED** [review]

**Comment by kwasniew** [comment]
@mikklfr your changes have been just published: https://pub.dev/packages/unleash_proxy_client_flutter

**Pull request merged**
